### ISSUE TITLE
ESA is not being installed

### ISSUE THREAD

**Issue by givanse** [sane/sane-auth#17]
Ember has a build error with:

```
Path or pattern "bower_components/ember-simple-auth/simple-auth.amd.js" did not match any files
```

and if I manually check the folder:

```
ls client/bower_components/ember-simple*
ls: cannot access client/bower_components/ember-simple*: No such file or directory
```

I tried to solve it with

```
cd client/
ember install ember-cli-simple-auth
```

and got this:

```
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /home/ivan/programming/sane-auth-example/client/node_modules/ember-cli/lib/models/project.js:475:53
    at baseFindIndex (/home/ivan/programming/sane-auth-example/client/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
```

**Comment by givanse** [comment]
not a `sane-auth` issue

The problem is this: https://github.com/ember-cli/ember-cli/issues/4085
